### ISSUE TITLE
Inconsistency in list_id type

### ISSUE THREAD

**Issue by jpic** [WoLpH/mailjet#10]
`list_id` is returned as an int in `api.lists.create()`
<pre>
   ipdb> n
   > env/src/mailjet/mailjet/contrib/django_mailjet/forms.py(67)list_create()
        66         l = self.api.lists.create(label=self.list_label, name=self.list_name,
   ---> 67                 method='POST')
        68  
   
   ipdb> 
   > env/src/mailjet/mailjet/contrib/django_mailjet/forms.py(69)list_create()
        67                 method='POST')
        68  
   ---> 69         return l['list_id']
   
   ipdb> print l
   {u'status': u'OK', u'list_id': 398253}
</pre>

But as a unicode string in `api.lists.all()`:                                            

<pre>
   ---> 34         for l in self.api.lists.all()['lists']:
         35             if l['id'] == list_id:

    ipdb> print l
    {u'name': u'foo', u'spam': u'0', u'created_at': u'1378992123', u'bounce': u'0', u'label': u'bar', u'click': u'0', u'last_activity': None, u'handled': u'1', u'subscribers': u'0', u'unsub': u'0', u'open': u'0', u'id': u'398253', u'sent': u'0', u'blocked': u'0'}
</pre>

And of course, this results in odd results:

    ipdb> print l['id'] == list_id
    False
    ipdb> print list_id
    398246
    ipdb> print l['id']
    398246

I know it's probably a bug from mailjet.com API, but maybe we could fix this inside the python mailjet package or maybe you could recommend a best practice (convert all to string ?)

Thanks

**Comment by WoLpH** [comment]
I expect that mailjet fixed the issue in APIv3 and even if they haven't. This API is now deprecated regardless so I think there is no further use for this issue
